### PR TITLE
Updating to react v15

### LINKED ISSUE #5: Update React to v15
In the other repository, you wanted to update the project, rewriting the app in the current version of React... Do you still want to do this? I believe I can help.

Note: Since the project is using `react-router: v2.0.0` and other packages that are incompatible with `React v16`, we can't jump to `React v16` directly. We need to move to `React v15` first, update other packages to version compatibles with `React v16` and then move to it.

What do you think, @bluetch? I can take care of this.

### PR DESCRIPTION
**Pull request by arthurdenner**
This closes #5. I removed some apparently unnecessary code, so make sure to test everything before accepting the merge, please.

### CODE REVIEW

**Comment by bluetch** [comment]
@arthurdenner , thanks for your help! I would like to ask about can I get your commit file before merge, I am new in github

**Comment by arthurdenner** [comment]
I think you need to run `git pull origin pull/:ID/head:BRANCHNAME` to get the files on your local repo.

In this case, try to run `git pull origin pull/10/head:update-react`. This should create a branch named `update-react` on your local repo.

[Reference](https://stackoverflow.com/questions/27567846/how-can-i-check-out-a-github-pull-request)

**Comment by bluetch** [comment]
Hi @arthurdenner , I checked it, it's all work! just a little CSS color miss, but I can do it, thank you :)

**Comment by bluetch** [comment]
Hi @arthurdenner , could you help me check below?

**Pull request merged**
